// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using restful_api.Data;

namespace restful_api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("restful_api.Modals.CricketModal", b =>
                {
                    b.Property<int>("CricketerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("BattingAvg")
                        .HasColumnType("double precision");

                    b.Property<double>("BowlingAvg")
                        .HasColumnType("double precision");

                    b.Property<string>("CrickterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Matches")
                        .HasColumnType("integer");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Wickets")
                        .HasColumnType("integer");

                    b.HasKey("CricketerId");

                    b.ToTable("Cricket");
                });

            modelBuilder.Entity("restful_api.Modals.FieldHockey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Apperance")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hockey");
                });

            modelBuilder.Entity("restful_api.Modals.FootballModal", b =>
                {
                    b.Property<int>("FootballerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Assist")
                        .HasColumnType("integer");

                    b.Property<string>("FootballerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Matches")
                        .HasColumnType("integer");

                    b.Property<int>("RedCard")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCard")
                        .HasColumnType("integer");

                    b.HasKey("FootballerId");

                    b.ToTable("Soccer");
                });
#pragma warning restore 612, 618
        }
    }
}
